name: my_movie_db
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  chopper: ^4.0.5
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  json_annotation: ^4.5.0
  logging: ^1.0.2

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  chopper_generator: ^4.0.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
